### ISSUE TITLE
Apply the algorithm to Go game

### ISSUE THREAD

**Issue by RuWang15** [aijunbai/thompson-sampling#1]
The algorithm is great! I want to apply the DNG-MCTS to go game (reward is winning rate ranging 0~1), but I'm confused about how to adjust the parameters in NormalGammaDistribution to fit the reward. Can you give me some advise? and did you try this before?

**Comment by aijunbai** [comment]
Please see page 4 to 5 of paper https://aijunbai.github.io/publications/NIPS13-Bai.pdf . It might not be very intuitive to adjust these parameters, but some simple principles (as described in the paper) may help. Good luck!
